controller:
    admin:
        username: admin
        password: admin123

    serviceType: LoadBalancer
    servicePort: 80
    service:
        port: 80
        targetPort: 8080

    resources:
        limits:
            cpu: "500m"
            memory: "1Gi"
        requests:
            cpu: "250m"
            memory: "512Mi"

    persistentVolume:
        enabled: true
        storageClass: "ebs-sc"
        size: 10Gi

    installPlugins:
        - kubernetes:latest
        - workflow-aggregator:latest
        - git:latest
        - configuration-as-code:latest
        - credentials-binding:latest
        - github:latest
        - docker-plugin:latest
        - docker-workflow:latest
        - job-dsl:latest
        - pipeline-stage-view:latest
        - build-timeout:latest
        - timestamper:latest
        - ws-cleanup:latest
        - ant:latest
        - gradle:latest
        - workflow-cps-global-lib:latest
        - pipeline-github-lib:latest
        - pipeline-stage-tags-metadata:latest
        - pipeline-graph-analysis:latest
        - pipeline-input-step:latest
        - pipeline-rest-api:latest
        - pipeline-stage-step:latest
        - pipeline-utility-steps:latest
        - plain-credentials:latest
        - ssh-credentials:latest
        - matrix-auth:latest
        - slack:latest
        - email-ext:latest
        - mailer:latest
        - aws-credentials:latest
        - amazon-ecr:latest

    serviceAccount:
        name: jenkins-sa
        create: false

    JCasC:
        configScripts:
            credentials: |
                credentials:
                  system:
                    domainCredentials:
                      - credentials:
                          - usernamePassword:
                              scope: GLOBAL
                              id: github-token
                              username: "oleksbod"
                              password: "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"
                              description: GitHub PAT
            seed-job: |
                jobs:
                  - script: >
                      job('seed-job') {
                        description('Job to generate pipeline for Django project')
                        scm {
                          git {
                            remote {
                              url('https://github.com/oleksbod/DevOpsCICD.git')
                              credentials('github-token')
                            }
                            branches('*/main')
                          }
                        }
                        steps {
                          dsl {
                            text('''
                              pipelineJob("django-cicd-pipeline") {
                                description('Full CI/CD Pipeline for Django Application')
                                definition {
                                  cpsScm {
                                    scm {
                                      git {
                                        remote {
                                          url("https://github.com/oleksbod/DevOpsCICD.git")
                                          credentials("github-token")
                                        }
                                        branches("*/main")
                                      }
                                    }
                                    scriptPath("Jenkinsfile")
                                  }
                                }
                                triggers {
                                  githubPush()
                                }
                                properties {
                                  pipelineTriggers {
                                    triggers {
                                      githubPush()
                                    }
                                  }
                                }
                              }
                              
                              pipelineJob("django-build-only") {
                                description('Build and Test Django Application')
                                definition {
                                  cpsScm {
                                    scm {
                                      git {
                                        remote {
                                          url("https://github.com/oleksbod/DevOpsCICD.git")
                                          credentials("github-token")
                                        }
                                        branches("*/main")
                                      }
                                    }
                                    scriptPath("Jenkinsfile.build")
                                  }
                                }
                              }
                              
                              pipelineJob("django-deploy") {
                                description('Deploy Django Application to Kubernetes')
                                definition {
                                  cpsScm {
                                    scm {
                                      git {
                                        remote {
                                          url("https://github.com/oleksbod/DevOpsCICD.git")
                                          credentials("github-token")
                                        }
                                        branches("*/main")
                                      }
                                    }
                                    scriptPath("Jenkinsfile.deploy")
                                  }
                                }
                              }
                            ''')
                          }
                        }
                      }
