apiVersion: v1
kind: Service
metadata:
  name: "{{ include "django-app.fullname" . }}"
  labels:
    app: "{{ include "django-app.name" . }}"
  {{- if .Values.monitoring.prometheus.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "{{ .Values.monitoring.prometheus.path }}"
  {{- end }}
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: "{{ include "django-app.name" . }}"
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP

