controller:
    admin:
        username: admin
        password: admin123

    serviceType: LoadBalancer
    servicePort: 80
    service:
        port: 80
        targetPort: 8080

    resources:
        limits:
            cpu: "300m"
            memory: "512Mi"
        requests:
            cpu: "100m"
            memory: "256Mi"

    persistentVolume:
        enabled: true
        storageClass: "ebs-sc"
        size: 10Gi

    installPlugins:
        - kubernetes:latest
        - workflow-aggregator:latest
        - git:latest
        - configuration-as-code:latest
        - credentials-binding:latest
        - github:latest
        - docker-plugin:latest
        - docker-workflow:latest
        - job-dsl:latest

    serviceAccount:
        name: jenkins-sa
        create: false

    JCasC:
        configScripts:
            credentials: |
                credentials:
                  system:
                    domainCredentials:
                      - credentials:
                          - usernamePassword:
                              scope: GLOBAL
                              id: github-token
                              username: ${GITHUB_USERNAME}
                              password: ${GITHUB_TOKEN}
                              description: GitHub PAT
            seed-job: |
                jobs:
                  - script: >
                      job('seed-job') {
                        description('Job to generate pipeline for Django project')
                        scm {
                          git {
                            remote {
                              url('https://github.com/oleksbod/DevOpsCICD.git')
                              credentials('github-token')
                            }
                            branches('*/main')
                          }
                        }
                        steps {
                          dsl {
                            text('''
                              pipelineJob("goit-django-docker") {
                                definition {
                                  cpsScm {
                                    scm {
                                      git {
                                        remote {
                                          url("https://github.com/oleksbod/DevOpsCICD.git")
                                          credentials("github-token")
                                        }
                                        branches("*/main")
                                      }
                                    }
                                  }
                                }
                              }
                            ''')
                          }
                        }
                      }
