{{- range .Values.repositories }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-repo
  namespace: {{ $.Values.namespace | default "argocd" }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: {{ .type | default "git" }}
  url: {{ .url }}
  {{- if .username }}
  username: {{ .username }}
  {{- end }}
  {{- if .password }}
  password: {{ .password }}
  {{- end }}
  {{- if .sshPrivateKey }}
  sshPrivateKey: {{ .sshPrivateKey }}
  {{- end }}
  {{- if .insecure }}
  insecure: {{ .insecure | quote }}
  {{- end }}
  {{- if .enableLfs }}
  enableLfs: {{ .enableLfs | quote }}
  {{- end }}
{{- end }}
