{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision | default "HEAD" }}
    path: {{ .source.path }}
    {{- if .source.helm }}
    helm:
      {{- if .source.helm.valueFiles }}
      valueFiles:
        {{- range .source.helm.valueFiles }}
        - {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}
  syncPolicy:
    {{- if .syncPolicy.automated }}
    automated:
      prune: {{ .syncPolicy.automated.prune | default false }}
      selfHeal: {{ .syncPolicy.automated.selfHeal | default false }}
    {{- end }}
    {{- if .syncPolicy.syncOptions }}
    syncOptions:
      {{- range .syncPolicy.syncOptions }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- if .syncPolicy.retry }}
    retry:
      limit: {{ .syncPolicy.retry.limit | default 5 }}
      backoff:
        duration: {{ .syncPolicy.retry.backoff.duration | default "5s" }}
        factor: {{ .syncPolicy.retry.backoff.factor | default 2 }}
        maxDuration: {{ .syncPolicy.retry.backoff.maxDuration | default "3m" }}
    {{- end }}
{{- end }}
