image:
    repository: "535138320407.dkr.ecr.eu-central-1.amazonaws.com/lesson-8-9-django"
    tag: "latest"
    pullPolicy: IfNotPresent

service:
    type: LoadBalancer
    port: 80
    targetPort: 8000

resources:
    requests:
        cpu: "50m"
        memory: "128Mi"
    limits:
        cpu: "200m"
        memory: "256Mi"

autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70

# Перенеси сюди ENV з теми 4
env:
    DJANGO_SETTINGS_MODULE: "config.settings"
    SECRET_KEY: "change-me"
    DEBUG: "false"
    ALLOWED_HOSTS: "*"

    POSTGRES_HOST: "db"
    POSTGRES_PORT: "5432"
    POSTGRES_USER: "django_user"
    POSTGRES_DB: "django_db"
    POSTGRES_PASSWORD: "pass9764gd"

ingress:
    enabled: false
    className: nginx
    host: yourdomain.com
    path: /
    pathType: Prefix
    tls: false
