server:
    service:
        type: LoadBalancer
        port: 443

    config:
        url: "https://argocd.example.com"

    extraArgs:
        - --insecure

    resources:
        limits:
            cpu: "500m"
            memory: "1Gi"
        requests:
            cpu: "250m"
            memory: "512Mi"

controller:
    resources:
        limits:
            cpu: "500m"
            memory: "1Gi"
        requests:
            cpu: "250m"
            memory: "512Mi"

repoServer:
    resources:
        limits:
            cpu: "500m"
            memory: "1Gi"
        requests:
            cpu: "250m"
            memory: "512Mi"

applicationSet:
    resources:
        limits:
            cpu: "500m"
            memory: "1Gi"
        requests:
            cpu: "250m"
            memory: "512Mi"
